In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [3]:
# df = pd.read_excel("ukraine_crisis_details.xlsx",sheet_name=None)
# df1 = pd.read_excel("yemen_crisis_details.xlsx",sheet_name=None)
# df2 = pd.read_excel("afghanistan_crisis_details.xlsx",sheet_name=None)
# df3 = pd.read_excel("turkiye_syria_earthquake_crisis_details.xlsx",sheet_name=None)
# df4 = pd.read_excel("crises_details.xlsx",sheet_name=None)

#### Create ExcelFile object to know the sheets names

### Afghanistan Data

In [2]:
# Create an ExcelFile object
excel_file = pd.ExcelFile("afghanistan_crisis_details.xlsx")

# Get the list of sheet names
sheet_names = excel_file.sheet_names

# Print the sheet names
print(sheet_names)

['Sheet1', 'wfp_food_prices', 'non_food_prices', 'reach_food_basket', 'reach_multi_item_prices', 'acled', 'ipc_current']

#### By using sheet_name = None you can access all the sheets

In [3]:
sheets_dict = pd.read_excel("afghanistan_crisis_details.xlsx", sheet_name=None)

In [4]:
wfp_food_prices_Af = sheets_dict["wfp_food_prices"]
non_food_prices_AF = sheets_dict["non_food_prices"]
reach_food_basket_AF = sheets_dict["reach_food_basket"]
reach_multi_item_prices_AF = sheets_dict["reach_multi_item_prices"]
acled_AF = sheets_dict["acled"]
ipc_current_AF = sheets_dict["ipc_current"]

In [5]:
print(wfp_food_prices_Af.columns)
print(wfp_food_prices_Af.shape)
wfp_food_prices_Af.head()

Index(['Unnamed: 0', 'id', 'date', 'admin1', 'pcode1', 'gid1', 'admin2',
       'pcode2', 'bread_kg', 'livestock', 'oil_kg', 'pulses_kg',
       'rice_lowquality_kg', 'salt_kg', 'sugar_kg', 'wheat_kg',
       'wheat_flour_kg', 'wheat_flour_highquality_kg',
       'wheat_flour_lowquality_kg', '_internal_filter_date'],
      dtype='object')
(3679, 20)

,Unnamed: 0,id,date,admin1,pcode1,gid1,admin2,pcode2,bread_kg,livestock,oil_kg,pulses_kg,rice_lowquality_kg,salt_kg,sugar_kg,wheat_kg,wheat_flour_kg,wheat_flour_highquality_kg,wheat_flour_lowquality_kg,_internal_filter_date
0,0,1,2000-01-15,['Hirat'],['AF32'],['AFG.12_1'],Hirat,AF3201,15.63,NaN,NaN,NaN,NaN,NaN,NaN,9.13,10.06,NaN,NaN,2000-01-15
1,1,2,2000-01-15,['Kabul'],['AF01'],['AFG.14_1'],Kabul,AF0101,14.26,NaN,NaN,NaN,NaN,NaN,NaN,13.75,18.57,NaN,NaN,2000-01-15
2,2,3,2000-01-15,['Kandahar'],['AF27'],['AFG.15_1'],Kandahar,AF2701,16.25,NaN,NaN,NaN,NaN,NaN,NaN,12.88,18.00,NaN,NaN,2000-01-15
3,3,4,2000-01-15,['Nangarhar'],['AF06'],['AFG.22_1'],Jalalabad,AF0601,14.86,NaN,NaN,NaN,NaN,NaN,NaN,13.16,15.55,NaN,NaN,2000-01-15
4,4,5,2000-02-15,['Hirat'],['AF32'],['AFG.12_1'],Hirat,AF3201,15.63,NaN,NaN,NaN,NaN,NaN,NaN,9.13,9.88,NaN,NaN,2000-02-15

In [6]:
print(non_food_prices_AF.columns)
print(non_food_prices_AF.shape)

non_food_prices_AF.head()

Index(['Unnamed: 0', 'id', 'date', 'admin1', 'pcode1', 'gid1', 'admin2',
       'pcode2', 'exchange_rate', 'fuel_diesel', 'wage_non_qualified_labor',
       'wage_qualified_labor', '_internal_filter_date'],
      dtype='object')
(2707, 13)

,Unnamed: 0,id,date,admin1,pcode1,gid1,admin2,pcode2,exchange_rate,fuel_diesel,wage_non_qualified_labor,wage_qualified_labor,_internal_filter_date
0,0,1,2000-01-15,['Badakhshan'],['AF17'],['AFG.1_1'],Fayzabad,AF1701,NaN,NaN,150000.0,NaN,2000-01-15
1,1,2,2000-01-15,['Balkh'],['AF21'],['AFG.4_1'],Mazar-e-Sharif,AF2101,NaN,NaN,100000.0,NaN,2000-01-15
2,2,3,2000-01-15,['Hirat'],['AF32'],['AFG.12_1'],Hirat,AF3201,NaN,NaN,60000.0,NaN,2000-01-15
3,3,4,2000-01-15,['Kabul'],['AF01'],['AFG.14_1'],Kabul,AF0101,NaN,NaN,55000.0,NaN,2000-01-15
4,4,5,2000-01-15,['Kandahar'],['AF27'],['AFG.15_1'],Kandahar,AF2701,NaN,NaN,75000.0,NaN,2000-01-15

In [7]:
print(reach_food_basket_AF.columns)
print(reach_food_basket_AF.shape)

reach_food_basket_AF.head()

Index(['Unnamed: 0', 'id', 'date', 'admin1', 'pcode1', 'gid1', 'admin2',
       'pcode2', 'region', 'food_basket_afn', 'meb_afn',
       '_internal_filter_date'],
      dtype='object')
(2097, 12)

,Unnamed: 0,id,date,admin1,pcode1,gid1,admin2,pcode2,region,food_basket_afn,meb_afn,_internal_filter_date
0,0,1,2022-07-01,['Badghis'],['AF31'],['AFG.2_1'],Ab Kamari,AF3102,Western,7049.00,19817.79,2022-07-01
1,1,2,2022-07-01,['Hirat'],['AF32'],['AFG.12_1'],Adraskan,AF3209,Western,8840.00,21787.89,2022-07-01
2,2,3,2022-07-01,['Paktya'],['AF13'],['AFG.26_1'],Ahmadaba,AF1302,South Eastern,8620.01,21545.90,2022-07-01
3,3,4,2022-07-01,['Kapisa'],['AF02'],['AFG.16_1'],Alasay,AF0207,Capital,7624.54,20450.88,2022-07-01
4,4,5,2022-07-01,['Faryab'],['AF29'],['AFG.8_1'],Almar,AF2904,Northern,9368.00,22368.69,2022-07-01

In [8]:
print(reach_multi_item_prices_AF.columns)
print(reach_multi_item_prices_AF.shape)

reach_multi_item_prices_AF.head()

Index(['Unnamed: 0', 'id', 'date', 'admin1', 'pcode1', 'gid1', 'admin2',
       'pcode2', 'region', 'wheat_local_price', 'wheat_imported_price',
       'local_rice_price', 'veg_oil_price', 'pulses_merged_price_final',
       'salt_price', 'sugar_price', 'tomatoes_price', 'pen_price',
       'notebook_price', 'rubber_price', 'cotton_cloth_price',
       'toothbrush_adult_price', 'toothpaste_price', 'sanitary_pad_price',
       'coal_price', 'soap_price', 'lpg_price', 'diesel_price', 'petrol_price',
       'buy_rate', 'sell_rate', 'safe_water_price',
       'safe_water_price_include_jerrycan', 'firewood_price',
       'pulses_lentils_price', 'pulses_beans_price', 'pulses_split_peas_price',
       'winter_jacket_price', 'water_container_price', 'cooking_pot_price',
       'blanket_price', 'cooking_fuel_price', '_internal_filter_date'],
      dtype='object')
(2211, 43)

,Unnamed: 0,id,date,admin1,pcode1,gid1,admin2,pcode2,region,wheat_local_price,...,firewood_price,pulses_lentils_price,pulses_beans_price,pulses_split_peas_price,winter_jacket_price,water_container_price,cooking_pot_price,blanket_price,cooking_fuel_price,_internal_filter_date
0,0,1,2022-07-01,['Badghis'],['AF31'],['AFG.2_1'],Ab Kamari,AF3102,Western,47.00,...,NaN,80.00,130.00,81.00,NaN,NaN,NaN,NaN,NaN,2022-07-01
1,1,2,2022-07-01,['Hirat'],['AF32'],['AFG.12_1'],Adraskan,AF3209,Western,42.50,...,13.33,100.00,80.00,55.00,650.0,265.0,1100.0,950.0,77.5,2022-07-01
2,2,3,2022-07-01,['Paktya'],['AF13'],['AFG.26_1'],Ahmadaba,AF1302,South Eastern,48.20,...,11.70,132.86,114.29,114.29,550.0,270.0,1100.0,1300.0,80.0,2022-07-01
3,3,4,2022-07-01,['Kapisa'],['AF02'],['AFG.16_1'],Alasay,AF0207,Capital,48.98,...,14.29,117.50,115.00,105.00,NaN,270.0,975.0,1000.0,80.0,2022-07-01
4,4,5,2022-07-01,['Faryab'],['AF29'],['AFG.8_1'],Almar,AF2904,Northern,NaN,...,NaN,NaN,132.50,100.00,NaN,NaN,NaN,NaN,NaN,2022-07-01

In [9]:
print(acled_AF.columns)
print(acled_AF.shape)

acled_AF.head()

Index(['Unnamed: 0', 'id', 'date', 'admin1', 'pcode1', 'gid1', 'admin2',
       'pcode2', 'event_type', 'sub_event_type', 'sub_event_number',
       '_internal_filter_date'],
      dtype='object')
(27703, 12)

,Unnamed: 0,id,date,admin1,pcode1,gid1,admin2,pcode2,event_type,sub_event_type,sub_event_number,_internal_filter_date
0,0,1,2017-01-01,['Badakhshan'],['AF17'],['AFG.1_1'],Arghanj Khwah,AF1703,Battles,Armed clash,1,2017-01-01
1,1,2,2017-01-01,['Badakhshan'],['AF17'],['AFG.1_1'],Baharak,AF1706,Battles,Armed clash,2,2017-01-01
2,2,3,2017-01-01,['Badakhshan'],['AF17'],['AFG.1_1'],Darwaz-e-Payin,AF1722,Battles,Government regains territory,1,2017-01-01
3,3,4,2017-01-01,['Badakhshan'],['AF17'],['AFG.1_1'],Fayzabad,AF1701,Battles,Armed clash,7,2017-01-01
4,4,5,2017-01-01,['Badakhshan'],['AF17'],['AFG.1_1'],Fayzabad,AF1701,Explosions/Remote violence,Remote explosive/landmine/IED,1,2017-01-01

In [10]:
print(ipc_current_AF.columns)
print(ipc_current_AF.shape)

ipc_current_AF.head()

Index(['Unnamed: 0', 'id', 'date', 'admin1', 'pcode1', 'gid1', 'analysis_name',
       'analysis_date', 'country_pop_number', 'country_pop_percent',
       'area_phase', 'analysis_period', 'number_ipc1', 'percent_ipc1',
       'number_ipc2', 'percent_ipc2', 'number_ipc3', 'percent_ipc3',
       'number_ipc4', 'percent_ipc4', 'number_ipc5', 'percent_ipc5',
       'number_ipc3_plus', 'percent_ipc3_plus', '_internal_filter_date'],
      dtype='object')
(417, 25)

,Unnamed: 0,id,date,admin1,pcode1,gid1,analysis_name,analysis_date,country_pop_number,country_pop_percent,...,percent_ipc2,number_ipc3,percent_ipc3,number_ipc4,percent_ipc4,number_ipc5,percent_ipc5,number_ipc3_plus,percent_ipc3_plus,_internal_filter_date
0,0,1,2018-09-01,['Badakhshan'],['AF17'],['AFG.1_1'],Acute Food Insecurity September 2018,Sep 2018,976602,NaN,...,0.30,410173,0.42,175788,0.18,0,0.0,585961,0.60,2018-09-01
1,1,2,2018-09-01,['Badghis'],['AF31'],['AFG.2_1'],Acute Food Insecurity September 2018,Sep 2018,514413,NaN,...,0.15,154324,0.30,231486,0.45,0,0.0,385810,0.75,2018-09-01
2,2,3,2018-09-01,['Baghlan'],['AF09'],['AFG.3_1'],Acute Food Insecurity September 2018,Sep 2018,776046,NaN,...,0.30,271616,0.35,38802,0.05,0,0.0,310418,0.40,2018-09-01
3,3,4,2018-09-01,['Balkh'],['AF21'],['AFG.4_1'],Acute Food Insecurity September 2018,Sep 2018,892684,NaN,...,0.30,312439,0.35,44634,0.05,0,0.0,357073,0.40,2018-09-01
4,4,5,2018-09-01,['Bamyan'],['AF10'],['AFG.5_1'],Acute Food Insecurity September 2018,Sep 2018,464370,NaN,...,0.30,208967,0.45,46437,0.10,0,0.0,255404,0.55,2018-09-01

### Turkiye_Syria data

In [11]:
# Create an ExcelFile object
excel_file1 = pd.ExcelFile("turkiye_syria_earthquake_crisis_details.xlsx")

# Get the list of sheet names
sheet_turkey = excel_file1.sheet_names

# Print the sheet names
print(sheet_turkey)

['Sheet1', 'events-timeline', 'seasonal-calendar', 'humanitarian-access-events', 'risk-list', 'protection', 'information-landscape']

In [26]:
sheets_dict1 = pd.read_excel("turkiye_syria_earthquake_crisis_details.xlsx", sheet_name=None)

In [28]:
events_timeline = sheets_dict1['events-timeline']
seasonal_calendar = sheets_dict1['seasonal-calendar']
humanitarian_access = sheets_dict1['humanitarian-access-events']
risk_list = sheets_dict1['risk-list']
protection = sheets_dict1['protection']
information_landscape= sheets_dict1['information-landscape']

In [29]:
print(events_timeline.columns)
print(events_timeline.shape)

events_timeline.head()

Index(['Unnamed: 0', 'id', 'iso', 'country', 'adm1', 'adm1_eng_name',
       'start_date', 'end_date', 'event', 'event_type', 'comment', 'source',
       'source_date', 'source_link', '_internal_filter_date'],
      dtype='object')
(16, 15)

,Unnamed: 0,id,iso,country,adm1,adm1_eng_name,start_date,end_date,event,event_type,comment,source,source_date,source_link,_internal_filter_date
0,0,1066,['SYR'],['Syria'],"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...","['Al Ḥasakah', 'Aleppo', 'Ar Raqqah', ""As Suwa...",2022-01-27,NaN,['Winter storm/ Snow season'],['Seasonal hazard'],"People living in the West Bank, Lebanon, Syria...",washingtonpost,2022-01-27,https://www.washingtonpost.com/world/2022/01/2...,2022-01-27
1,1,1321,['SYR'],['Syria'],SYR.2_1,['Aleppo'],2022-09-10,NaN,['Cholera'],['Outbreak'],The SARG declared a cholera outbreak on Septem...,USAID,2022-09-15,https://reliefweb.int/report/syrian-arab-repub...,2022-09-10
2,2,1322,['SYR'],['Syria'],"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...","['Al Ḥasakah', 'Aleppo', 'Ar Raqqah', ""As Suwa...",2022-04-01,2022-06-30,['Drought'],['Seasonal hazard'],The World Meteorological Organization (WMO) se...,OCHA,2022-09-15,https://reliefweb.int/report/syrian-arab-repub...,2022-04-01
3,3,1327,['TUR'],['Türkiye'],TUR.58_1,['Mersin'],2022-09-07,NaN,['Wildfire'],['Seasonal hazard'],A forest fire broke out in Gülnar District (Me...,ECHO,2022-09-09,https://reliefweb.int/report/turkiye/turkey-fo...,2022-09-07
4,4,2153,['TUR'],['Türkiye'],"TUR.1_1, TUR.2_1, TUR.26_1, TUR.33_1, TUR.37_1...","['Adana', 'Adiyaman', 'Diyarbakir', 'Gaziantep...",2023-02-06,2023-02-06,['Earthquake '],['Natural disaster'],"Edinburg, TX - Over 150 people have been kille...",UOSSM,2023-02-06,https://reliefweb.int/report/syrian-arab-repub...,2023-02-06

In [16]:
print(seasonal_calendar.columns)
print(seasonal_calendar.shape)

seasonal_calendar.head()

Index(['Unnamed: 0', 'id', 'iso', 'country', 'country_wide', 'adm1',
       'adm1_eng_name', 'months', 'event', 'event_type', 'label', 'comment',
       'source', 'source_date', 'source_link'],
      dtype='object')
(48, 15)

,Unnamed: 0,id,iso,country,country_wide,adm1,adm1_eng_name,months,event,event_type,label,comment,source,source_date,source_link
0,0,1835,['SYR'],['Syria'],True,"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...",NaN,"['October', 'November', 'December']",['1st/main planting'],['Planting and growing'],['Barley'],Barely planting,USDA,2022-07-14,https://ipad.fas.usda.gov/rssiws/al/crop_calen...
1,1,1836,['SYR'],['Syria'],True,"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...",NaN,"['May', 'June']",['2nd harvest'],['Harvest'],['Barley'],Barely harvest,USDA,2022-07-14,https://ipad.fas.usda.gov/rssiws/al/crop_calen...
2,2,1837,['SYR'],['Syria'],True,"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...",NaN,"['March', 'April', 'May']",['1st/main planting'],['Planting and growing'],['Maize'],Corn planting,USDA,2022-07-14,https://ipad.fas.usda.gov/rssiws/al/crop_calen...
3,3,1838,['SYR'],['Syria'],True,"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...",NaN,"['August', 'September']",['1st/main harvest'],['Harvest'],['Maize'],Corn harvest,USDA,2022-07-14,https://ipad.fas.usda.gov/rssiws/al/crop_calen...
4,4,1839,['SYR'],['Syria'],True,"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...",NaN,"['April', 'May']",['1st/main planting'],['Planting and growing'],['Cotton'],Cotton planting,USDA,2022-07-14,https://ipad.fas.usda.gov/rssiws/al/crop_calen...

In [17]:
print(humanitarian_access.columns)
print(humanitarian_access.shape)

humanitarian_access.head()

Index(['Unnamed: 0', 'event_id', 'country', 'iso3', 'country_wide', 'adm1',
       'adm1_name', 'indicator', 'subindicator',
       'targeting_specific_population_groups', 'event_date', 'description',
       'source_name', 'source_date', 'source_link', 'additional_sources'],
      dtype='object')
(501, 16)

,Unnamed: 0,event_id,country,iso3,country_wide,adm1,adm1_name,indicator,subindicator,targeting_specific_population_groups,event_date,description,source_name,source_date,source_link,additional_sources
0,0,10032,['Türkiye'],['TUR'],False,['TUR.34_1'],['Giresun'],['I9 - Environmental constraints'],"['S9.1 - Rainy season (e.g. snow, monsoon, sea...",['Other population groups relevant in a context'],NaN,Floods and landslides occurred in Giresun due ...,NTV,2023-06-24,https://www.ntv.com.tr/galeri/turkiye/giresund...,NaN
1,1,1070,['Syria'],['SYR'],False,['SYR.1_1'],['Al Ḥasakah'],['I4 - Restriction of movement within the coun...,['S4.3 - Checkpoints towards or in the affecte...,NaN,NaN,Al Hol camp has an annex separated from the ma...,World Vision,2022-04-11,https://www.wvi.org/sites/default/files/2022-0...,NaN
2,2,10714,['Syria'],['SYR'],True,NaN,NaN,['I2 - Restriction and obstruction of access t...,['S2.1 - Physical obstruction to service acces...,['Other population groups relevant in a context'],NaN,"Despite the exceptions, sanctions affect human...",HRW,2023-06-22,https://www.hrw.org/news/2023/06/22/questions-...,NaN
3,3,10715,['Syria'],['SYR'],True,NaN,NaN,['I2 - Restriction and obstruction of access t...,['S2.3 - The forced displacement of people in ...,['Other population groups relevant in a context'],NaN,"Despite the exceptions, sanctions affect human...",HRW,2023-06-22,https://www.hrw.org/news/2023/06/22/questions-...,NaN
4,4,10716,['Syria'],['SYR'],True,NaN,NaN,['I5 - Interference into implementation of hum...,['S5.1 - Authorities or other groups imposing ...,['Other population groups relevant in a context'],NaN,"Despite the exceptions, sanctions affect human...",HRW,2023-06-22,https://www.hrw.org/news/2023/06/22/questions-...,NaN

In [30]:
print(risk_list.columns)
print(risk_list.shape)

risk_list.head()

Index(['Unnamed: 0', 'risk_id', 'country', 'iso3', 'risk_title', 'crisis_id',
       'geographic_level', 'risk_type', 'date_entered', 'last_risk_update',
       'published', 'publication_link', 'rationale', 'trigger', 'exposure',
       'intensity', 'vulnerability', 'impact', 'probability', 'risk_level',
       'status', '_internal_filter_date'],
      dtype='object')
(14, 22)

,Unnamed: 0,risk_id,country,iso3,risk_title,crisis_id,geographic_level,risk_type,date_entered,last_risk_update,...,rationale,trigger,exposure,intensity,vulnerability,impact,probability,risk_level,status,_internal_filter_date
0,0,R0001,['Syria'],['SYR'],A full-scale offensive on northwestern Syria l...,['SYR001'],Subnational,New emerging risk,2019-06-01,2024-06-13T13:53:48.000Z,...,An offensive on opposition-held northwest Syri...,Further advancement and increased Government o...,">500,000",5.0,Preexisting vulnerabilities and exhausted copi...,5.0,Low,Medium,Not materialised,2024-06-13
1,1,R0009,"['Iran', 'United States', 'Yemen', 'Iraq', 'Sy...","['IRN', 'USA', 'YEM', 'IRQ', 'SYR', 'AFG']",Heightened tensions between Iran and the US an...,"['YEM001', 'SYR001', 'IRQ002']",Regional,New emerging risk,2019-06-01,2024-06-13T13:53:51.000Z,...,A series of events have raised fears of an esc...,Increased a conflict between US forces and Ira...,">500,000",3.0,Preexisting vulnerabilities and climatic shock...,2.0,Low,Medium,Not materialised,2024-06-13
2,2,R0028,['Syria'],['SYR'],The closure of the al Yaorubia crossing worsen...,['SYR001'],Subnational,New emerging risk,2020-01-16,2024-06-13T13:53:51.000Z,...,The humanitarian response has been significant...,Closing of the Yaroubia crossing.,">500,000",4.0,Preexisting vulnerabilities and exhausted copi...,4.0,High,High,Materialised,2024-06-13
3,3,R0057,['Syria'],['SYR'],"The economic crisis escalates, with thousands ...",['SYR001'],National,Marked deterioration in an existing crisis,2020-03-12,2024-06-13T13:53:58.000Z,...,"No substantial economic reforms, no access to ...","- Further currency depreciation, inflation, ba...",">500,000",5.0,Preexisting vulnerabilities and exhausted copi...,5.0,High,High,Materialised,2024-06-13
4,4,R0075,['Syria'],['SYR'],The intensification of attacks on civilian cen...,['SYR001'],Subnational,New emerging risk,2021-01-14,2024-06-13T13:53:58.000Z,...,"Turkish-backed and Syrian National Army (SNA),...",Intensification of bomb attacks against civili...,">500,000",3.0,Preexisting vulnerabilities and exhausted copi...,3.0,Medium,Medium,Materialised,2024-06-13

In [19]:
print(protection.columns)
print(protection.shape)

protection.head()

Index(['Unnamed: 0', 'entry_id', 'iso3', 'country', 'countrywide', 'adm1',
       'adm1_eng_name', 'indicator', 'targeting_specific_population_groups',
       'justification', 'source_name', 'source_date', 'source_link',
       'additional_sources', '_internal_filter_date'],
      dtype='object')
(775, 15)

,Unnamed: 0,entry_id,iso3,country,countrywide,adm1,adm1_eng_name,indicator,targeting_specific_population_groups,justification,source_name,source_date,source_link,additional_sources,_internal_filter_date
0,0,P00059,['TUR'],['Türkiye'],True,"TUR.1_1, TUR.2_1, TUR.3_1, TUR.4_1, TUR.5_1, T...","['Adana', 'Adiyaman', 'Afyon', 'Agri', 'Aksara...",['Violence/abuse/intolerance towards individua...,['Gender'],Turkey's withdrawal from the convention marks ...,ACLED,2022-08-04,https://reliefweb.int/report/yemen/acled-regio...,NaN,2022-08-04
1,1,P00353,['SYR'],['Syria'],True,"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...","['Al Ḥasakah', 'Aleppo', 'Ar Raqqah', 'As Suwa...",['Child labour'],['Age'],7-year-old child who had taken work lubricatin...,concern worldwide,2022-05-16,https://www.concern.net/news/syrian-children-c...,NaN,2022-05-16
2,2,P00354,['SYR'],['Syria'],True,"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...","['Al Ḥasakah', 'Aleppo', 'Ar Raqqah', 'As Suwa...",['Child labour'],['Age'],It’s common for young boys to work in machiner...,concern worldwide,2022-05-16,https://www.concern.net/news/syrian-children-c...,NaN,2022-05-16
3,3,P00356,['SYR'],['Syria'],True,"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...","['Al Ḥasakah', 'Aleppo', 'Ar Raqqah', 'As Suwa...",['Forced and/or early marriage'],"['Age', 'Gender']",Girls are also more likely to marry at an earl...,concern worldwide,2022-05-16,https://www.concern.net/news/syrian-children-c...,NaN,2022-05-16
4,4,P00358,['SYR'],['Syria'],True,"SYR.1_1, SYR.2_1, SYR.3_1, SYR.4_1, SYR.5_1, S...","['Al Ḥasakah', 'Aleppo', 'Ar Raqqah', 'As Suwa...",['Children being associated with armed forces ...,['Age'],Syrian youths voluntarily joined armed groups ...,concern worldwide,2022-05-16,https://www.concern.net/news/syrian-children-c...,NaN,2022-05-16

In [20]:
print(information_landscape.columns)
print(information_landscape.shape)

information_landscape.head()

Index(['Unnamed: 0', 'entry_id', 'iso3', 'country', 'countrywide', 'adm1',
       'adm1_eng_name', 'indicator', 'subindicator', 'entry_type',
       'justification', 'source_name', 'source_date', 'source_link', 'created',
       '_internal_filter_date'],
      dtype='object')
(750, 16)

,Unnamed: 0,entry_id,iso3,country,countrywide,adm1,adm1_eng_name,indicator,subindicator,entry_type,justification,source_name,source_date,source_link,created,_internal_filter_date
0,0,I00474,['TUR'],['Türkiye'],False,['TUR.1_1'],['Adana'],['ILI4 - Information freedom and security'],['ILS4.1 - Journalist safety'],Event,"113 years ago, a journalist was murdered in Tu...",Binat,2022-04-06,https://m.bianet.org/english/freedom-of-expres...,2022-10-11,2022-04-06
1,1,I00475,['TUR'],['Türkiye'],False,['TUR.41_1'],['Izmir'],['ILI4 - Information freedom and security'],['ILS4.1 - Journalist safety'],Event,"February 19, 2022, Turkish journalist Güngör ...",CPJ,2022-02-19,https://cpj.org/2022/02/turkish-journalist-gun...,2022-10-11,2022-02-19
2,2,I00777,['TUR'],['Türkiye'],True,NaN,NaN,['ILI1 - Information trends '],['ILS1.1 - Disinformation trends'],Trend,"Turkey has long been hell for journalists, Tur...",CNBC,2022-10-21,https://www.cnbc.com/2022/10/21/turkish-report...,2022-10-21,2022-10-21
3,3,I00778,['TUR'],['Türkiye'],True,NaN,NaN,['ILI1 - Information trends '],['ILS1.1 - Disinformation trends'],Trend,Turkish officials shot back at Greek allegatio...,Voanews,2022-10-16,https://www.voanews.com/a/turkey-calls-greek-c...,2022-10-21,2022-10-16
4,4,I00779,['TUR'],['Türkiye'],True,NaN,NaN,['ILI1 - Information trends '],['ILS1.1 - Disinformation trends'],Trend,Erdoğan began to argue that Turkey’s highly-po...,EURACTIV,2022-10-14,https://www.euractiv.com/section/global-europe...,2022-10-22,2022-10-14

### Ukraine data

In [3]:
# Create an ExcelFile object
excel_file2 = pd.ExcelFile("ukraine_crisis_details.xlsx")

# Get the list of sheet names
sheet_Ukraine = excel_file2.sheet_names

# Print the sheet names
print(sheet_Ukraine)

['access_events', 'damages', 'master_log', 'regional_log']

In [4]:
sheets_dict2 = pd.read_excel("ukraine_crisis_details.xlsx",sheet_name =None )

In [6]:
access_events = sheets_dict2['access_events']
damages = sheets_dict2['damages']
master_log = sheets_dict2['master_log']
regional_log = sheets_dict2['regional_log']

In [7]:
print(access_events.columns)
print(access_events.shape)

access_events.head()

Index(['Unnamed: 0', 'event_id', 'source_name', 'iso3', 'country', 'gid_1',
       'oblast', 'pcode', 'rayon', 'event_type', 'if_other_specify', 'pillar',
       'indicator', 'subindicator', 'date_of_event', 'source_date',
       'source_link', 'additional_sources', '_internal_filter_date', '_weight',
       'not_active'],
      dtype='object')
(8125, 21)

,Unnamed: 0,event_id,source_name,iso3,country,gid_1,oblast,pcode,rayon,event_type,...,pillar,indicator,subindicator,date_of_event,source_date,source_link,additional_sources,_internal_filter_date,_weight,not_active
0,0,100,OCHA,UKR,['Ukraine'],['UKR.8_1'],Kharkivska,UA63,Kharkivskyi,Conditions affecting human resources of humani...,...,Access of humanitarian actors to affected popu...,I5 - Interference with implementation of human...,S5.1 - Conditions imposed by authorities or ot...,2022-03-31,2022-04-01,https://reliefweb.int/report/ukraine/ukraine-h...,NaN,2022-03-31,0.7,False
1,1,1000,UN,UKR,['Ukraine'],['UKR.6_1'],Donetska,UA14,NaN,Suspected contaminated area,...,Physical and security constraints,I8 - Presence of mines and explosive devices,S8.2 - Other contaminated area (sqkm),NaN,2022-04-20,https://news.un.org/en/story/2022/04/1116562,NaN,2022-04-20,1.0,False
2,2,10000,Ukrainska pravda,UKR,['Ukraine'],['UKR.19_1'],Rivnenska,UA56,NaN,Movement restrictions for people seeking safet...,...,Access of people in need to aid,I2 - Restriction and obstruction to access ser...,S2.1 - Physical obstruction to access to servi...,2023-11-08,2023-11-08,https://www.pravda.com.ua/news/2023/11/8/7427790/,NaN,2023-11-08,1.0,False
3,3,10001,Ukrainska pravda,UKR,['Ukraine'],['UKR.21_1'],Sumska,UA59,NaN,Movement restrictions for people seeking safet...,...,Access of people in need to aid,I2 - Restriction and obstruction to access ser...,S2.1 - Physical obstruction to access to servi...,2023-11-08,2023-11-08,https://www.pravda.com.ua/news/2023/11/8/7427790/,NaN,2023-11-08,1.0,False
4,4,10002,Ukrainska pravda,UKR,['Ukraine'],['UKR.22_1'],Ternopilska,UA61,NaN,Movement restrictions for people seeking safet...,...,Access of people in need to aid,I2 - Restriction and obstruction to access ser...,S2.1 - Physical obstruction to access to servi...,2023-11-08,2023-11-08,https://www.pravda.com.ua/news/2023/11/8/7427790/,NaN,2023-11-08,1.0,False

In [8]:
print(damages.columns)
print(damages.shape)

damages.head()

Index(['Unnamed: 0', 'damage_id', 'iso3', 'country', 'gid_1', 'oblast',
       'rayon', 'type_of_infrastructure', 'if_other_what', 'date_of_event',
       'source_name', 'source_date', 'source_link', 'additional_sources',
       'extent_of_damage', '_internal_filter_date', '_weights',
       'access_subindicator', 'pcode'],
      dtype='object')
(14782, 19)

,Unnamed: 0,damage_id,iso3,country,gid_1,oblast,rayon,type_of_infrastructure,if_other_what,date_of_event,source_name,source_date,source_link,additional_sources,extent_of_damage,_internal_filter_date,_weights,access_subindicator,pcode
0,0,D0011,UKR,Ukraine,['UKR.15_1'],Luhanska,Sievierodonetskyi,Warehouse,NaN,2022-03-25,OCHA,2022-03-28,https://reliefweb.int/report/ukraine/ukraine-h...,NaN,Destroyed,2022-03-25,0.7,['7.2'],UA44
1,1,D0012,UKR,Ukraine,['UKR.15_1'],Luhanska,Sievierodonetskyi,Warehouse,NaN,2022-03-26,OCHA,2022-03-28,https://reliefweb.int/report/ukraine/ukraine-h...,NaN,Partially damaged,2022-03-26,0.7,['7.2'],UA44
2,2,D0015,UKR,Ukraine,['UKR.14_1'],Lvivska,NaN,Warehouse,NaN,2022-03-26,OCHA,2022-03-28,https://reliefweb.int/report/ukraine/ukraine-h...,NaN,Unknown,2022-03-26,1.0,['7.2'],UA46
3,3,D0016,UKR,Ukraine,['UKR.14_1'],Lvivska,NaN,Aircraft repair plant,Aircraft repair plan,2022-03-26,OCHA,2022-03-28,https://reliefweb.int/report/ukraine/ukraine-h...,NaN,Destroyed,2022-03-26,1.0,['7.2'],UA46
4,4,D0017,UKR,Ukraine,['UKR.12_1'],Kyivska,NaN,Bridge,NaN,2022-03-22,OCHA,2022-03-28,https://reliefweb.int/report/ukraine/ukraine-h...,NaN,Destroyed,2022-03-22,1.0,['9.2'],UA32

In [9]:
print(master_log.columns)
print(master_log.shape)

master_log.head()

Index(['Unnamed: 0', 'log_id', 'iso3', 'country', 'gid_1', 'oblast_or_country',
       'pillar', 'indicator', 'subindicator', 'figure', 'justification',
       'source_link', 'source_name', 'source_date', 'data_date',
       '_internal_filter_date', 'pcode'],
      dtype='object')
(6966, 17)

,Unnamed: 0,log_id,iso3,country,gid_1,oblast_or_country,pillar,indicator,subindicator,figure,justification,source_link,source_name,source_date,data_date,_internal_filter_date,pcode
0,0,12,UKR,Ukraine,NaN,Ukraine,Crisis impact,Affected groups,# outgoing refugees since February 2022,3032612.0,This is the number of outgoing refugees from U...,https://data.humdata.org/dataset/ukraine-refug...,UNHCR,2022-05-31,NaN,2022-05-31,NaN
1,1,22,UKR,Ukraine,NaN,Ukraine,Crisis impact,Affected groups,# people in need,17718000.0,"This is the number of people in need, accordin...",https://reliefweb.int/report/ukraine/ukraine-f...,OCHA,2022-08-08,NaN,2022-08-08,NaN
2,2,25,UKR,Ukraine,UKR.1_1,Cherkaska,Crisis impact,Affected groups,# people in need,400000.0,This is the number of people in need.,https://reliefweb.int/report/ukraine/ukraine-f...,OCHA,2022-08-08,NaN,2022-08-08,UA71
3,3,26,UKR,Ukraine,UKR.2_1,Chernihivska,Crisis impact,Affected groups,# people in need,483000.0,This is the number of people in need.,https://reliefweb.int/report/ukraine/ukraine-f...,OCHA,2022-08-08,NaN,2022-08-08,UA74
4,4,27,UKR,Ukraine,UKR.3_1,Chernivetska,Crisis impact,Affected groups,# people in need,341000.0,This is the number of people in need.,https://reliefweb.int/report/ukraine/ukraine-f...,OCHA,2022-08-08,NaN,2022-08-08,UA73

In [10]:
print(regional_log.columns)
print(regional_log.shape)

regional_log.head()

Index(['Unnamed: 0', 'log_id', 'iso3', 'country', 'pillar', 'indicator',
       'figure', 'justification', 'source_link', 'source_name', 'source_date',
       '_internal_filter_date'],
      dtype='object')
(872, 12)

,Unnamed: 0,log_id,iso3,country,pillar,indicator,figure,justification,source_link,source_name,source_date,_internal_filter_date
0,0,4,CZE,Czech Republic,Baseline demography,# of nationals who are members of the Ukrainia...,170960.0,78068 people with one ethnic identity (Ukraini...,https://vdb.czso.cz/vdbvo2/faces/en/index.jsf?...,Czech Statistical Office,NaN,2021-05-11
1,1,5,HUN,Hungary,Baseline demography,# of nationals who are members of the Ukrainia...,10996.0,Ukrainian ethnic minority as of 2016,https://www.ksh.hu/docs/hun/xftp/idoszaki/mikr...,Hungarian Central Statistical Office,2018-12-31,2016-11-08
2,2,6,MDA,Moldova,Baseline demography,# of nationals who are members of the Ukrainia...,181035.0,The number of ethnic Ukrainians in Moldova as ...,https://statistica.gov.md/files/files/Recensam...,National Bureau of Statistics of the Republic ...,NaN,2014-05-25
3,3,7,POL,Poland,Baseline demography,# of nationals who are members of the Ukrainia...,79400.0,Ethnic Ukrainians in Poland according to the N...,https://stat.gov.pl/spisy-powszechne/nsp-2021/...,Polish Central Statistical Office,NaN,2021-12-31
4,4,8,ROU,Romania,Baseline demography,# of nationals who are members of the Ukrainia...,50920.0,Ethnic Ukrainians in Romania as of 2011 accord...,https://www.recensamantromania.ro/rpl-2011/rez...,Government of Romania,NaN,2011-01-01

### Yemen data

In [11]:
# Create an ExcelFile object
excel_file3 = pd.ExcelFile("yemen_crisis_details.xlsx")

# Get the list of sheet names
sheet_Yemen = excel_file3.sheet_names

# Print the sheet names
print(sheet_Yemen)

['economy', 'conflict', 'displace_and_return', 'non_yemeni_migrants', 'pin_and_severity', 'ipc_governorate', 'ipc_district', 'nutrition', 'health', 'wash', 'education', 'livelihoods', 'agency_presence']

In [12]:
sheets_dict3 = pd.read_excel("yemen_crisis_details.xlsx", sheet_name= None)

In [13]:
economy = sheets_dict3["economy"]
conflict = sheets_dict3["conflict"]
displace_and_return = sheets_dict3["displace_and_return"]
non_yemeni_migrants = sheets_dict3["non_yemeni_migrants"]
pin_and_severity = sheets_dict3["pin_and_severity"]
ipc_governorate = sheets_dict3["ipc_governorate"]
ipc_district = sheets_dict3["ipc_district"]
nutrition = sheets_dict3["nutrition"]
health = sheets_dict3["health"]
wash = sheets_dict3["wash"]
education = sheets_dict3["education"]
livelihoods = sheets_dict3["livelihoods"]
agency_presence = sheets_dict3["agency_presence"]

In [14]:
print(economy.columns)
print(economy.shape)

economy.head()

Index(['Unnamed: 0', 'id', 'date', 'unocha_operational_hub', 'governorate',
       'gid_1', 'pcode_1', 'exchange_rate_unofficial_wfp_vam',
       'fuel_diesel_wfp_vam', 'fuel_gas_wfp_vam', 'fuel_petrol_wfp_vam',
       'water_price_reach', 'min_survival_food_basket_cost_wfp_vam',
       'exhange_rate_unofficial_fao', 'diesel_official_fao',
       'diesel_unofficial_fao', 'gas_cylinder_official_fao',
       'gas_cylinder_unofficial_fao', 'petrol_official_fao',
       'petrol_unofficial_fao', 'min_survival_food_basket_cost_fao',
       '_internal_filter_date'],
      dtype='object')
(4018, 22)

,Unnamed: 0,id,date,unocha_operational_hub,governorate,gid_1,pcode_1,exchange_rate_unofficial_wfp_vam,fuel_diesel_wfp_vam,fuel_gas_wfp_vam,...,min_survival_food_basket_cost_wfp_vam,exhange_rate_unofficial_fao,diesel_official_fao,diesel_unofficial_fao,gas_cylinder_official_fao,gas_cylinder_unofficial_fao,petrol_official_fao,petrol_unofficial_fao,min_survival_food_basket_cost_fao,_internal_filter_date
0,0,1,2009-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-01-01
1,1,2,2009-01-01,Aden,"[""Ad Dali'""]",['YEM.4_1'],['YE30'],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-01-01
2,2,3,2009-01-01,Aden,['Aden'],['YEM.1_1'],['YE24'],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-01-01
3,3,4,2009-01-01,Sana'a,['Al Bayda'],['YEM.3_1'],['YE14'],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-01-01
4,4,5,2009-01-01,Al Hudaydah,['Al Hodeidah'],['YEM.5_1'],['YE18'],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-01-01

In [15]:
print(conflict.columns)
print(conflict.shape)

conflict.head()

Index(['Unnamed: 0', 'id', 'date', 'unocha_operational_hub', 'governorate',
       'gid_1', 'pcode_1', 'district', 'pcode_2', 'gid_2',
       'civilian_casualties', 'damage_civilian_structures',
       'damage_critical_infrastructures', 'critical_infrastructure_type',
       'uxo_landmines_incidents', 'air_strikes', 'conflict_incidents',
       'actors', '_internal_filter_date'],
      dtype='object')
(21656, 19)

,Unnamed: 0,id,date,unocha_operational_hub,governorate,gid_1,pcode_1,district,pcode_2,gid_2,civilian_casualties,damage_civilian_structures,damage_critical_infrastructures,critical_infrastructure_type,uxo_landmines_incidents,air_strikes,conflict_incidents,actors,_internal_filter_date
0,0,1,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Ahwar'],['YE1209'],['YEM.2.1_1'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01
1,1,2,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Al Mahfad'],['YE1201'],['YEM.2.2_1'],7.0,2.0,NaN,NaN,3.0,NaN,6.0,NaN,2019-01-01
2,2,3,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],"[""Al Wadi'""]",['YE1208'],['YEM.2.3_1'],NaN,NaN,NaN,NaN,3.0,NaN,1.0,NaN,2019-01-01
3,3,4,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Jayshan'],['YE1203'],['YEM.2.4_1'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01
4,4,5,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Khanfar'],['YE1211'],['YEM.2.5_1'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01

In [16]:
print(displace_and_return.columns)
print(displace_and_return.shape)

displace_and_return.head()

Index(['Unnamed: 0', 'id', 'date', 'unocha_operational_hub', 'governorate',
       'gid_1', 'pcode_1', 'district', 'pcode_2', 'gid_2',
       'idp_hh_displaced_monthly', 'est_idp_individuals_displaced_monthly',
       'idp_hh_displaced_annual_cumulative', 'idp_hh_displaced_to_monthly',
       'est_idp_individuals_displaced_to_monthly',
       'idp_hh_displaced_to_annual_cumulative',
       'returnee_hh_returning_monthly',
       'est_returnee_individuals_returning_monthly',
       'returnee_hh_returning_cumulative', 'idp_hh_isolated_dispersed_monthly',
       'est_idp_individuals_isolated_dispersed_monthly',
       'idp_hh_settlement_urban_rural_monthly',
       'est_idp_individuals_settlement_urban_rural_monthly',
       '_internal_filter_date'],
      dtype='object')
(19417, 24)

,Unnamed: 0,id,date,unocha_operational_hub,governorate,gid_1,pcode_1,district,pcode_2,gid_2,...,est_idp_individuals_displaced_to_monthly,idp_hh_displaced_to_annual_cumulative,returnee_hh_returning_monthly,est_returnee_individuals_returning_monthly,returnee_hh_returning_cumulative,idp_hh_isolated_dispersed_monthly,est_idp_individuals_isolated_dispersed_monthly,idp_hh_settlement_urban_rural_monthly,est_idp_individuals_settlement_urban_rural_monthly,_internal_filter_date
0,0,1,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Ahwar'],['YE1209'],['YEM.2.1_1'],...,0,0.0,NaN,0,0.0,0.0,0.0,0.0,0.0,2019-01-01
1,1,2,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Al Mahfad'],['YE1201'],['YEM.2.2_1'],...,0,0.0,NaN,0,0.0,0.0,0.0,0.0,0.0,2019-01-01
2,2,3,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],"[""Al Wadi'""]",['YE1208'],['YEM.2.3_1'],...,0,0.0,NaN,0,0.0,0.0,0.0,0.0,0.0,2019-01-01
3,3,4,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Jayshan'],['YE1203'],['YEM.2.4_1'],...,0,0.0,NaN,0,0.0,0.0,0.0,0.0,0.0,2019-01-01
4,4,5,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Khanfar'],['YE1211'],['YEM.2.5_1'],...,252,42.0,NaN,0,0.0,0.0,0.0,0.0,0.0,2019-01-01

In [17]:
print(non_yemeni_migrants.columns)
print(non_yemeni_migrants.shape)

non_yemeni_migrants.head()

Index(['Unnamed: 0', 'id', 'date', 'country', 'governorate', 'gid_1',
       'pcode_1', 'district', 'pcode_2', 'gid_2', 'fmp_code', 'fmp', 'sub_fmp',
       'interview_date', 'transport_mean', 'departure_admin0',
       'departure_admin1', 'departure_admin2', 'departure_city_other',
       'destination_admin0', 'destination_admin1', 'destination_city',
       'destination_city_other', 'migration_type', 'flow_type',
       'total_individuals', 'men', 'women', 'boys', 'girls',
       'pregnant_or_lactating', 'children_below_5', 'unaccompanied_minors',
       'people_with_disabilities', 'elderly', 'ethiopian', 'somalis',
       'other_natinality', 'total_migrants', 'yemenis', 'migrant_returnee',
       'eritirians', 'djiboutians', 'malian', 'nigerian', 'bangladeshi',
       'syrian', 'longitude', 'latitude', '_internal_filter_date'],
      dtype='object')
(6559, 50)

,Unnamed: 0,id,date,country,governorate,gid_1,pcode_1,district,pcode_2,gid_2,...,migrant_returnee,eritirians,djiboutians,malian,nigerian,bangladeshi,syrian,longitude,latitude,_internal_filter_date
0,0,1,2022-01-01,Yemen,['Hadramawt'],['YEM.12_1'],['YE19'],['Al Abr'],['YE1906'],['YEM.12.3_1'],...,Returnee,0.0,0.0,0.0,0.0,0.0,0.0,47.01496,16.94404,2022-01-01
1,1,2,2022-01-01,Yemen,['Hadramawt'],['YEM.12_1'],['YE19'],['Al Abr'],['YE1906'],['YEM.12.3_1'],...,Returnee,0.0,0.0,0.0,0.0,0.0,0.0,47.01496,16.94404,2022-01-01
2,2,3,2022-01-01,Yemen,['Hadramawt'],['YEM.12_1'],['YE19'],['Al Madaribah Wa Al Aarah'],['YE2513'],['YEM.15.3_1'],...,Returnee,0.0,0.0,0.0,0.0,0.0,0.0,47.01496,16.94404,2022-01-01
3,3,4,2022-01-01,Yemen,['Lahj'],['YEM.15_1'],['YE25'],['Al Abr'],['YE1906'],['YEM.12.3_1'],...,Migrant,0.0,0.0,0.0,0.0,0.0,0.0,43.80395,12.69264,2022-01-01
4,4,5,2022-01-01,Yemen,['Hadramawt'],['YEM.12_1'],['YE19'],['Al Abr'],['YE1906'],['YEM.12.3_1'],...,Returnee,0.0,0.0,0.0,0.0,0.0,0.0,47.01496,16.94404,2022-01-01

In [18]:
print(pin_and_severity.columns)
print(pin_and_severity.shape)

pin_and_severity.head()

Index(['Unnamed: 0', 'id', 'date', 'unocha_operational_hub', 'governorate',
       'gid_1', 'pcode_1', 'district', 'pcode_2', 'gid_2',
       'severity_intercluster', 'pin_intercluster', 'severity_wash',
       'pin_wash', 'severity_fsac', 'pin_fsac', 'severity_protection',
       'pin_protection', 'severity_education', 'pin_education',
       'severity_health', 'pin_health', 'severity_shelter', 'pin_shelter',
       'severity_nutrition', 'pin_nutrition', 'severity_cccm', 'pin_cccm',
       'severity_rmms', 'pin_rmms', 'severity_gbv', 'total_pin_gbv',
       'severity_mine_action', 'total_pin_mine_action',
       'severity_child_protection', 'total_pin_child_protection',
       'severity_rrm', 'total_pin_rrm', '_internal_filter_date'],
      dtype='object')
(8991, 39)

,Unnamed: 0,id,date,unocha_operational_hub,governorate,gid_1,pcode_1,district,pcode_2,gid_2,...,pin_rmms,severity_gbv,total_pin_gbv,severity_mine_action,total_pin_mine_action,severity_child_protection,total_pin_child_protection,severity_rrm,total_pin_rrm,_internal_filter_date
0,0,1,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Ahwar'],['YE1209'],['YEM.2.1_1'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01
1,1,2,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Al Mahfad'],['YE1201'],['YEM.2.2_1'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01
2,2,3,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],"[""Al Wadi'""]",['YE1208'],['YEM.2.3_1'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01
3,3,4,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Jayshan'],['YE1203'],['YEM.2.4_1'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01
4,4,5,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Khanfar'],['YE1211'],['YEM.2.5_1'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01

In [19]:
print(ipc_governorate.columns)
print(ipc_governorate.shape)

ipc_governorate.head()

Index(['Unnamed: 0', 'id', 'date_of_analysis', 'governorate', 'gid_1',
       'pcode_1', 'population', 'figures_type', 'analysis_period', 'phase1',
       'phase1_percent', 'phase2', 'phase2_percent', 'phase3',
       'phase3_percent', 'phase4', 'phase4_percent', 'phase5',
       'phase5_percent', 'phase_p3plus', 'phase_p3plus_percent',
       '_internal_filter_date'],
      dtype='object')
(139, 22)

,Unnamed: 0,id,date_of_analysis,governorate,gid_1,pcode_1,population,figures_type,analysis_period,phase1,...,phase2_percent,phase3,phase3_percent,phase4,phase4_percent,phase5,phase5_percent,phase_p3plus,phase_p3plus_percent,_internal_filter_date
0,0,1,2018-12-01,['Abyan'],['YEM.2_1'],['YE12'],615154,Current,Dec 2018 - Jan 2019,125000,...,0.38,179000,0.29,79500,0.13,0,0.0,258500,0.42,2018-12-01
1,1,2,2018-12-01,['Aden'],['YEM.1_1'],['YE24'],997308,Current,Dec 2018 - Jan 2019,181500,...,0.36,284500,0.29,174000,0.17,0,0.0,458500,0.46,2018-12-01
2,2,3,2018-12-01,['Al Bayda'],['YEM.3_1'],['YE14'],775404,Current,Dec 2018 - Jan 2019,91500,...,0.32,315500,0.41,119500,0.15,1500,0.0,436500,0.56,2018-12-01
3,3,4,2018-12-01,"[""Ad Dali'""]",['YEM.4_1'],['YE30'],779656,Current,Dec 2018 - Jan 2019,122000,...,0.30,295000,0.38,129000,0.17,1500,0.0,425500,0.55,2018-12-01
4,4,5,2018-12-01,['Al Hodeidah'],['YEM.5_1'],['YE18'],2985122,Current,Dec 2018 - Jan 2019,526500,...,0.26,1126500,0.38,558500,0.19,6000,0.0,1691000,0.57,2018-12-01

In [20]:
print(ipc_district.columns)
print(ipc_district.shape)

ipc_district.head()

Index(['Unnamed: 0', 'id', 'date_of_analysis', 'governorate', 'gid_1',
       'pcode_1', 'district', 'pcode_2', 'gid_2', 'analysis_name',
       'population', 'area_phase', 'figures_type', 'analysis_period', 'phase1',
       'phase1_percent', 'phase2', 'phase2_percent', 'phase3',
       'phase3_percent', 'phase4', 'phase4_percent', 'phase5',
       'phase5_percent', 'phase_p3plus', 'phase_p3plus_percent',
       '_internal_filter_date'],
      dtype='object')
(1743, 27)

,Unnamed: 0,id,date_of_analysis,governorate,gid_1,pcode_1,district,pcode_2,gid_2,analysis_name,...,phase2_percent,phase3,phase3_percent,phase4,phase4_percent,phase5,phase5_percent,phase_p3plus,phase_p3plus_percent,_internal_filter_date
0,0,1,2018-12-01,['Abyan'],['YEM.2_1'],['YE12'],['Ahwar'],['YE1209'],['YEM.2.1_1'],Acute Food Insecurity December 2018,...,0.25,15477,0.45,3439,0.10,0,0.0,18916,0.55,2018-12-01
1,1,2,2018-12-01,['Abyan'],['YEM.2_1'],['YE12'],['Al Mahfad'],['YE1201'],['YEM.2.2_1'],Acute Food Insecurity December 2018,...,0.27,28093,0.35,13645,0.17,0,0.0,41738,0.52,2018-12-01
2,2,3,2018-12-01,['Abyan'],['YEM.2_1'],['YE12'],"[""Al Wadi'""]",['YE1208'],['YEM.2.3_1'],Acute Food Insecurity December 2018,...,0.53,2895,0.09,2574,0.08,0,0.0,5469,0.17,2018-12-01
3,3,4,2018-12-01,['Abyan'],['YEM.2_1'],['YE12'],['Jayshan'],['YE1203'],['YEM.2.4_1'],Acute Food Insecurity December 2018,...,0.30,6466,0.32,2425,0.12,0,0.0,8891,0.44,2018-12-01
4,4,5,2018-12-01,['Abyan'],['YEM.2_1'],['YE12'],['Khanfar'],['YE1211'],['YEM.2.5_1'],Acute Food Insecurity December 2018,...,0.35,63759,0.38,30201,0.18,0,0.0,93960,0.56,2018-12-01

In [21]:
print(nutrition.columns)
print(nutrition.shape)

nutrition.head()

Index(['Unnamed: 0', 'id', 'date', 'unocha_operational_hub', 'governorate',
       'gid_1', 'pcode_1', 'district', 'pcode_2', 'gid_2', 'gam_rate',
       'sam_rate', 'sam_caseload_2019', 'mam_caseload_2019',
       'plw_caseload_2019', '_internal_filter_date'],
      dtype='object')
(8325, 16)

,Unnamed: 0,id,date,unocha_operational_hub,governorate,gid_1,pcode_1,district,pcode_2,gid_2,gam_rate,sam_rate,sam_caseload_2019,mam_caseload_2019,plw_caseload_2019,_internal_filter_date
0,0,1,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Ahwar'],['YE12'],['YEM.2.1_1'],0.100,0.017,299.536203,1305.347245,825.432,2019-01-01
1,1,2,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Al Mahfad'],['YE12'],['YEM.2.2_1'],0.053,0.006,100.121193,946.145275,873.696,2019-01-01
2,2,3,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],"[""Al Wadi'""]",['YE12'],['YEM.2.3_1'],0.053,0.006,88.482008,836.154977,772.128,2019-01-01
3,3,4,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Jayshan'],['YE12'],['YEM.2.4_1'],0.053,0.006,55.569407,525.130900,484.920,2019-01-01
4,4,5,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Khanfar'],['YE12'],['YEM.2.5_1'],0.100,0.017,1461.285187,6368.127025,4026.864,2019-01-01

In [22]:
print(health.columns)
print(health.shape)

health.head()

Index(['Unnamed: 0', 'id', 'date', 'unocha_operational_hub', 'governorate',
       'gid_1', 'pcode_1', 'district', 'pcode_2', 'gid_2',
       'percent_functioning_health_centres', 'num_health_workers',
       'num_suspected_cases_cholera', 'num_deaths_cholera',
       'percent_attack_rate', 'percent_individuals_health_facilities_problems',
       'num_clinics', 'num_dentists', 'num_doctors', 'number_hospitals',
       'num_pharmacies', '_internal_filter_date'],
      dtype='object')
(7428, 22)

,Unnamed: 0,id,date,unocha_operational_hub,governorate,gid_1,pcode_1,district,pcode_2,gid_2,...,num_suspected_cases_cholera,num_deaths_cholera,percent_attack_rate,percent_individuals_health_facilities_problems,num_clinics,num_dentists,num_doctors,number_hospitals,num_pharmacies,_internal_filter_date
0,0,1,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Ahwar'],['YE1209'],['YEM.2.1_1'],...,0.0,NaN,0.000000,0.160706,NaN,NaN,NaN,NaN,NaN,2019-01-01
1,1,2,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Al Mahfad'],['YE1201'],['YEM.2.2_1'],...,1.0,NaN,0.274695,0.292978,NaN,NaN,NaN,NaN,NaN,2019-01-01
2,2,3,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],"[""Al Wadi'""]",['YE1208'],['YEM.2.3_1'],...,1.0,NaN,0.310829,0.097955,NaN,NaN,NaN,NaN,NaN,2019-01-01
3,3,4,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Jayshan'],['YE1203'],['YEM.2.4_1'],...,1.0,NaN,0.494927,0.231262,NaN,NaN,NaN,NaN,NaN,2019-01-01
4,4,5,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Khanfar'],['YE1211'],['YEM.2.5_1'],...,18.0,2.0,1.072795,0.192745,NaN,NaN,NaN,NaN,NaN,2019-01-01

In [23]:
print(wash.columns)
print(wash.shape)

wash.head()

Index(['Unnamed: 0', 'id', 'date', 'unocha_operational_hub', 'governorate',
       'gid_1', 'pcode_1', 'district', 'pcode_2', 'gid_2',
       'percent_ind_access_to_latrine', 'percent_ind_access_sufficient_water',
       '_internal_filter_date'],
      dtype='object')
(333, 13)

,Unnamed: 0,id,date,unocha_operational_hub,governorate,gid_1,pcode_1,district,pcode_2,gid_2,percent_ind_access_to_latrine,percent_ind_access_sufficient_water,_internal_filter_date
0,0,1,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Abyan'],['YE12'],['YEM.2.1_1'],85.0,84.0,2018-12-18
1,1,2,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Abyan'],['YE12'],['YEM.2.2_1'],59.0,76.0,2018-12-18
2,2,3,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Abyan'],['YE12'],['YEM.2.3_1'],94.0,64.0,2018-12-18
3,3,4,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Abyan'],['YE12'],['YEM.2.4_1'],77.0,68.0,2018-12-18
4,4,5,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Abyan'],['YE12'],['YEM.2.5_1'],71.0,75.0,2018-12-18

In [24]:
print(education.columns)
print(education.shape)

education.head()

Index(['Unnamed: 0', 'id', 'date', 'unocha_operational_hub', 'governorate',
       'gid_1', 'pcode_1', 'district', 'pcode_2', 'gid_2',
       'percent_non_functional_schools', '_internal_filter_date'],
      dtype='object')
(333, 12)

,Unnamed: 0,id,date,unocha_operational_hub,governorate,gid_1,pcode_1,district,pcode_2,gid_2,percent_non_functional_schools,_internal_filter_date
0,0,1,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Ahwar'],['YE1209'],['YEM.2.1_1'],0.0,2018-12-18
1,1,2,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Al Mahfad'],['YE1201'],['YEM.2.2_1'],0.0,2018-12-18
2,2,3,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],"[""Al Wadi'""]",['YE1208'],['YEM.2.3_1'],0.0,2018-12-18
3,3,4,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Jayshan'],['YE1203'],['YEM.2.4_1'],0.0,2018-12-18
4,4,5,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Khanfar'],['YE1211'],['YEM.2.5_1'],0.0,2018-12-18

In [25]:
print(livelihoods.columns)
print(livelihoods.shape)

livelihoods.head()

Index(['Unnamed: 0', 'id', 'date', 'unocha_operational_hub', 'governorate',
       'gid_1', 'pcode_1', 'district', 'pcode_2', 'gid_2',
       'percent_people_access_regular_income',
       'reduced_coping_strategies_index',
       'poor_to_borderline_food_consumptions_scores',
       'percent_ind_access_markets', '_internal_filter_date'],
      dtype='object')
(7326, 15)

,Unnamed: 0,id,date,unocha_operational_hub,governorate,gid_1,pcode_1,district,pcode_2,gid_2,percent_people_access_regular_income,reduced_coping_strategies_index,poor_to_borderline_food_consumptions_scores,percent_ind_access_markets,_internal_filter_date
0,0,1,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Ahwar'],['YE1209'],['YEM.2.1_1'],0.68,15.9,0.408,0.28,2018-12-18
1,1,2,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Al Mahfad'],['YE1201'],['YEM.2.2_1'],0.42,15.9,0.408,0.23,2018-12-18
2,2,3,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],"[""Al Wadi'""]",['YE1208'],['YEM.2.3_1'],0.57,15.9,0.408,0.21,2018-12-18
3,3,4,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Jayshan'],['YE1203'],['YEM.2.4_1'],0.49,15.9,0.408,0.19,2018-12-18
4,4,5,2018-12-18,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Khanfar'],['YE1211'],['YEM.2.5_1'],0.51,15.9,0.408,0.23,2018-12-18

In [26]:
print(agency_presence.columns)
print(agency_presence.shape)

agency_presence.head()

Index(['Unnamed: 0', 'id', 'date', 'unocha_operational_hub', 'governorate',
       'gid_1', 'pcode_1', 'district', 'pcode_2', 'gid_2', 'number_of_ingos',
       'number_of_lngos', 'number_of_un_agencies', '_internal_filter_date'],
      dtype='object')
(8658, 14)

,Unnamed: 0,id,date,unocha_operational_hub,governorate,gid_1,pcode_1,district,pcode_2,gid_2,number_of_ingos,number_of_lngos,number_of_un_agencies,_internal_filter_date
0,0,1,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Ahwar'],['YE1209'],['YEM.2.1_1'],9,6,7,2019-01-01
1,1,2,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Al Mahfad'],['YE1201'],['YEM.2.2_1'],9,6,7,2019-01-01
2,2,3,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],"[""Al Wadi'""]",['YE1208'],['YEM.2.3_1'],9,6,7,2019-01-01
3,3,4,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Jayshan'],['YE1203'],['YEM.2.4_1'],9,6,7,2019-01-01
4,4,5,2019-01-01,Aden,['Abyan'],['YEM.2_1'],['YE12'],['Khanfar'],['YE1211'],['YEM.2.5_1'],9,6,7,2019-01-01

### Crisis Details

In [27]:
crisis_details = pd.read_excel("crises_details.xlsx",sheet_name=None)

In [29]:
crisis = crisis_details['crises']
crisis_activation_log = crisis_details["crisis_activation_log"]

In [30]:
print(crisis.columns)
print(crisis.shape)

crisis.head()

Index(['Unnamed: 0', 'crisis_id', 'crisis_name', 'website_name', 'iso3',
       'country', 'regions', 'individual_aggregated', 'regional_or_country',
       'country_level', 'drivers', 'geoscope', 'adm1', 'adm1_name',
       'connected_crises', 'date_created', 'active'],
      dtype='object')
(329, 17)

,Unnamed: 0,crisis_id,crisis_name,website_name,iso3,country,regions,individual_aggregated,regional_or_country,country_level,drivers,geoscope,adm1,adm1_name,connected_crises,date_created,active
0,0,AFG001,Complex crisis in Afghanistan,Complex crisis,['AFG'],['Afghanistan'],['Asia'],Individual,Country,Yes,"['Conflict', 'Violence', 'Displacement', 'Drou...",National,NaN,NaN,['AFG005'],2020-10-21,True
1,1,AFG002,Conflict in Afghanistan,NaN,['AFG'],['Afghanistan'],['Asia'],Individual,Country,No,['Conflict'],NaN,NaN,NaN,NaN,2020-10-21,False
2,2,AFG003,Drought in Afghanistan,NaN,['AFG'],['Afghanistan'],['Asia'],Individual,Country,No,['Drought'],NaN,NaN,NaN,NaN,2020-10-21,False
3,3,AFG004,Floods in Afghanistan,NaN,['AFG'],['Afghanistan'],['Asia'],Individual,Country,No,['Floods'],NaN,NaN,NaN,NaN,2020-10-21,False
4,4,AFG005,Earthquake in Khost and Paktika,Earthquake in Khost and Paktika,['AFG'],['Afghanistan'],['Asia'],Individual,Country,No,['Earthquake'],Subnational,"['AFG.17_1', 'AFG.25_1']","['Khost', 'Paktika']",['AFG001'],2022-06-29,False

In [31]:
print(crisis_activation_log.columns)
print(crisis_activation_log.shape)

crisis_activation_log.head()

Index(['Unnamed: 0', 'id', 'crisis_id', 'date', 'activated_deactivated',
       '_internal_filter_date'],
      dtype='object')
(525, 6)

,Unnamed: 0,id,crisis_id,date,activated_deactivated,_internal_filter_date
0,0,1,AFG001,2019-01-01,Activated,2019-01-01
1,1,2,UGA006,2020-05-01,Activated,2020-05-01
2,2,3,LBY002,2019-01-01,Activated,2019-01-01
3,3,4,JOR003,2019-01-01,Activated,2019-01-01
4,4,5,TCD002,2019-01-01,Activated,2019-01-01

### Countries

In [32]:
country = pd.read_excel('countries.xlsx',sheet_name='countries')

In [33]:
print(country.columns)
print(country.shape)

country.head()

Index(['Unnamed: 0', 'iso3', 'country', 'regions', 'crises', 'overview'], dtype='object')
(248, 6)

,Unnamed: 0,iso3,country,regions,crises,overview
0,0,ABW,Aruba,Americas,NaN,NaN
1,1,AFG,Afghanistan,Asia,"['AFG001', 'AFG002', 'AFG003', 'AFG004', 'AFG0...",The drivers of the humanitarian crisis in Afgh...
2,2,AGO,Angola,Africa,['AGO002'],Southern Angola is facing a severe food crisis...
3,3,AIA,Anguilla,Americas,NaN,NaN
4,4,ALA,Åland Islands,Europe,NaN,NaN

In [34]:
### Risk_list

In [35]:
risk_list = pd.read_csv('risk_list.csv')

In [36]:
print(risk_list.columns)
print(risk_list.shape)

risk_list.head()

Index(['risk_id', 'country', 'iso3', 'risk_title', 'crisis_id',
       'geographic_level', 'risk_type', 'date_entered', 'last_risk_update',
       'published', 'publication_link', 'rationale', 'trigger', 'exposure',
       'intensity', 'vulnerability', 'impact', 'probability', 'risk_level',
       'status', '_internal_filter_date'],
      dtype='object')
(211, 21)

,risk_id,country,iso3,risk_title,crisis_id,geographic_level,risk_type,date_entered,last_risk_update,published,...,rationale,trigger,exposure,intensity,vulnerability,impact,probability,risk_level,status,_internal_filter_date
0,R0001,['Syria'],['SYR'],A full-scale offensive on northwestern Syria l...,['SYR001'],Subnational,New emerging risk,2019-06-01,2024-06-13T13:53:48.000Z,2019-06-01,...,An offensive on opposition-held northwest Syri...,Further advancement and increased Government o...,">500,000",5,Preexisting vulnerabilities and exhausted copi...,5.0,Low,Medium,Not materialised,2024-06-13
1,R0009,"['Iran', 'United States', 'Yemen', 'Iraq', 'Sy...","['IRN', 'USA', 'YEM', 'IRQ', 'SYR', 'AFG']",Heightened tensions between Iran and the US an...,"['YEM001', 'SYR001', 'IRQ002']",Regional,New emerging risk,2019-06-01,2024-06-13T13:53:51.000Z,2019-06-01,...,A series of events have raised fears of an esc...,Increased a conflict between US forces and Ira...,">500,000",3,Preexisting vulnerabilities and climatic shock...,2.0,Low,Medium,Not materialised,2024-06-13
2,R0011,['Bosnia and Herzegovina'],['BIH'],"The arrival of 50,000 migrants, refugees, and ...",['BIH002'],National,Marked deterioration in an existing crisis,2019-03-01,2024-06-13T13:53:51.000Z,2019-03-01,...,"24,000 migrants and refugees registered entry ...",- Improvement of weather and travel conditions,"20,000-100,000",NaN,"Migrants, refugees, and asylum seekers are hig...",1.0,Very Low,Low,Not materialised,2024-06-13
3,R0013,['Libya'],['LBY'],Increasing violence and consequent displacemen...,['LBY001'],Subnational,Marked deterioration in an existing crisis,2019-03-01,2024-06-13T13:53:51.000Z,2019-03-01,...,Recent developments in Libya have raised the r...,- Increasing violence\r\n- Increasing displace...,">500,000",3,A lack of availability and access to services ...,5.0,High,High,Not materialised,2024-06-13
4,R0028,['Syria'],['SYR'],The closure of the al Yaorubia crossing worsen...,['SYR001'],Subnational,New emerging risk,2020-01-16,2024-06-13T13:53:51.000Z,NaN,...,The humanitarian response has been significant...,Closing of the Yaroubia crossing.,">500,000",4,Preexisting vulnerabilities and exhausted copi...,4.0,High,High,Materialised,2024-06-13